- name: tar maria
  shell: tar xf /tmp/rpm/mariadb-5.5.36-linux-x86_64.tar.gz -C /usr/local/;
- name: ln mysql
  shell: ln -sv /usr/local/mariadb-5.5.36-linux-x86_64 /usr/local/mysql
- name: init mysql
  shell: /usr/local/mysql/scripts/mysql_install_db --user=mysql --basedir=/usr/local/mysql --datadir=/mydata/mariadb &
  tags: init
- name: confile
  copy: src={{ item }} dest=/etc/{{ item }}
  with_items:
    - my.cnf
    - profile
  tags: conf
- name: cp init
  shell: cp /usr/local/mysql/support-files/mysql.server /etc/init.d/mysqld
  tags: confile
- name: sourceprofiled
  shell: source /etc/profile
